config/routes.rb
Rails.application.routes.draw do

  resources :departures
  resources :trips
  resources :tracks
  resources :stations
  resources :statuses
  root 'home#index'

end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :station
  validates :number, presence: true
  validates :station_id, presence: true
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
    @station_options = [["Select Station",nil]] + Station.all.map {|st| [st.name, st.id]}
  end

  # GET /tracks/1/edit
  def edit
    @station_options = [["Select Station",nil]] + Station.all.map {|st| [st.name, st.id]}
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        @station_options = [["Select Station",nil]] + Station.all.map {|st| [st.name, st.id]}
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        @station_options = [["Select Station",nil]] + Station.all.map {|st| [st.name, st.id]}
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:number, :info, :station_id)
    end
end

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <%= render partial: "shared/create_errors", locals: {object: @track, name:"track"} %>
  <% end %>

<div class="input-group stpad">
    <span class="input-group-addon addon3">Number</span>
    <%= f.text_field :number, class:"form-control" %>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Station</span>
    <%= f.select :station_id, options_for_select(@station_options,:selected=>@track.station_id),{}, {:class => 'form-control'} %>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Info</span>
    <%= f.text_area :info, class:"form-control", :rows => "2",placeholder:"Optional" %>
  </div>


  <br>
  <div class="text-center stpad">
    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Cancel'.html_safe, tracks_path, class:"btn btn-default" %>
    <button role="button" type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-send"></i> Submit</button>

  </div>
<% end %>

app/views/tracks/_track.html.erb
<tr>
	<td><%= track.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
	<td><%= track.number %></td>
	<td><%= Station.find(track.station_id).name %></td>
	<td><%= track.info %></td>
	<td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, track, class:"pull-right btn btn-xs btn-info" %></td>
	<td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_track_path(track), class:"pull-right btn btn-xs btn-warning" %></td>
  	<td><%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'.html_safe, track,
               method: :delete,
               data: { confirm: 'Are you sure?' }, class:"pull-right btn btn-xs btn-danger" %></td>
</tr>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li class="active"><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-subway" aria-hidden="true"></i> Tracks Board <span class="badge"><%=@tracks.count%></span>
        <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Create New Track'.html_safe, new_track_path, class:"pull-right btn btn-success" %>
        </h4>
      </div>
      <div class="panel-body">
      <div class="table-responsive tableItem">
        <table id="table" class="table table-hover table-striped tablesorter">
          <thead>
            <tr>
              <th>Last Update  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Number  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Station  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Track Info  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= render @tracks %>
          </tbody>
        </table>
      </div>
      </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">

  $(document).ready(function() { 
    $("#table").tablesorter();
  });

</script>

app/views/tracks/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li class="active"><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-subway" aria-hidden="true"></i> New Track
        </h4>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      	<br/>
      	<%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Tracks'.html_safe, tracks_path, class:"pull-right btn btn-primary" %>
      </div>
    </div>
</div>

app/views/tracks/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li class="active"><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-subway" aria-hidden="true"></i> Track Info
        </h4>
      </div>
      <div class="panel-body">
      	<p>
		  <strong>Number:</strong>
		  <%= @track.number %>
		</p>

		<p>
		  <strong>Station:</strong>
		  <%= Station.find(@track.station_id).name %>
		</p>

		<p>
		  <strong>Info:</strong>
		  <%= @track.info %>
		</p>

		<br/>
        <div class="text-center stpad">
        <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_track_path(@track), class:"pull-left btn btn-warning" %>
        <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Tracks'.html_safe, tracks_path, class:"pull-right btn btn-primary" %>

      </div>
      </div>
    </div>
</div>