config/routes.rb
Rails.application.routes.draw do

  resources :departures
  resources :trips
  resources :tracks
  resources :stations
  resources :statuses
  root 'home#index'

end

app/models/station.rb
class Station < ActiveRecord::Base
	validates :name, presence: true
	has_many :tracks, dependent: :destroy
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :info)
    end
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <%= render partial: "shared/create_errors", locals: {object: @station, name:"station"} %>
  <% end %>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Name</span>
    <%= f.text_field :name,class:"form-control" %>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Info</span>
    <%= f.text_area :info, class:"form-control", :rows => "2",placeholder:"Optional" %>
  </div>


  <br>
  <div class="text-center stpad">
    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Cancel'.html_safe, stations_path, class:"btn btn-default" %>
    <button role="button" type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-send"></i> Submit</button>

  </div>
<% end %>

app/views/stations/_station.html.erb
<tr>
	<td><%= station.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
	<td><%= station.name %></td>
	<td><%= station.info %></td>
	<td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, station, class:"pull-right btn btn-xs btn-info" %></td>
	<td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_station_path(station), class:"pull-right btn btn-xs btn-warning" %></td>
  	<td><%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'.html_safe, station,
               method: :delete,
               data: { confirm: 'Are you sure?' }, class:"pull-right btn btn-xs btn-danger" %></td>
</tr>

app/views/stations/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li class="active"><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-building-o" aria-hidden="true"></i> Edit Station</h4>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      	<br/>
      	<div class="text-center stpad">
	      <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, @station, class:"pull-left btn btn-success" %>
  	    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Stations'.html_safe, stations_path, class:"pull-right btn btn-primary" %>

	    </div>
      </div>
    </div>
</div>

app/views/stations/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li class="active"><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-building-o" aria-hidden="true"></i> Stations Board <span class="badge"><%=@stations.count%></span>
        <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Create New Station'.html_safe, new_station_path, class:"pull-right btn btn-success" %>
        </h4>
      </div>
      <div class="panel-body">
      <div class="table-responsive tableItem">
        <table id="table" class="table table-hover table-striped tablesorter">
          <thead>
            <tr>
              <th>Last Update  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Name  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Station Info  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= render @stations %>
          </tbody>
        </table>
      </div>
      </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">

  $(document).ready(function() { 
    $("#table").tablesorter();
  });

</script>

app/views/stations/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li class="active"><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-building-o" aria-hidden="true"></i> New Station</h4>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      	<br/>
      	<%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Stations'.html_safe, stations_path, class:"pull-right btn btn-primary" %>
      </div>
    </div>
</div>

app/views/stations/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li class="active"><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa-building-o" aria-hidden="true"></i> Station Info
        </h4>
      </div>
      <div class="panel-body">
        
        <p>
		  <strong>Name:</strong>
		  <%= @station.name %>
		</p>

		<p>
		  <strong>Info:</strong>
		  <%= @station.info %>
		</p>
        <br/>
        <div class="text-center stpad">
        <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_station_path(@station), class:"pull-left btn btn-warning" %>
        <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Stations'.html_safe, stations_path, class:"pull-right btn btn-primary" %>

      </div>
      </div>
    </div>
</div>