config/routes.rb
Rails.application.routes.draw do

  resources :departures
  resources :trips
  resources :tracks
  resources :stations
  resources :statuses
  root 'home#index'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:given, :info)
    end
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <%= render partial: "shared/create_errors", locals: {object: @status, name:"status"} %>
  <% end %>

<div class="input-group stpad">
    <span class="input-group-addon addon3">Status</span>
    <%= f.text_field :given,class:"form-control" %>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Info</span>
    <%= f.text_area :info, class:"form-control", :rows => "2",placeholder:"Optional" %>
  </div>


  <br>
  <div class="text-center stpad">
    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Cancel'.html_safe, statuses_path, class:"btn btn-default" %>
    <button role="button" type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-send"></i> Submit</button>

  </div>
<% end %>

app/views/statuses/_status.html.erb
<tr>
	<td><%= status.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
	<td><%= status.given %></td>
	<td><%= status.info %></td>
	<td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, status, class:"pull-right btn btn-xs btn-info" %></td>
	<td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_status_path(status), class:"pull-right btn btn-xs btn-warning" %></td>
  	<td><%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'.html_safe, status,
               method: :delete,
               data: { confirm: 'Are you sure?' }, class:"pull-right btn btn-xs btn-danger" %></td>
</tr>

app/views/statuses/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li class="active"><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-info-circle" aria-hidden="true"></i> Edit Status
        </h4>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      	<br/>
      	<div class="text-center stpad">
	      <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, @status, class:"pull-left btn btn-success" %>
  	    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Statuses'.html_safe, statuses_path, class:"pull-right btn btn-primary" %>

	    </div>
      </div>
    </div>
</div>

app/views/statuses/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li class="active"><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-info-circle" aria-hidden="true"></i> Status Board <span class="badge"><%=@statuses.count%></span>
        <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Create New Status'.html_safe, new_status_path, class:"pull-right btn btn-success" %>
        </h4>
      </div>
      <div class="panel-body">
      <div class="table-responsive tableItem">
        <table id="table" class="table table-hover table-striped tablesorter">
          <thead>
            <tr>
              <th>Last Update  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Status  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>More Info  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= render @statuses %>
          </tbody>
        </table>
      </div>
      </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">

  $(document).ready(function() { 
    $("#table").tablesorter();
  });

</script>

app/views/statuses/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li class="active"><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-info-circle" aria-hidden="true"></i> New Status
        </h4>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      	<br/>
      	<%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Statuses'.html_safe, statuses_path, class:"pull-right btn btn-primary" %>
      </div>
    </div>
</div>

app/views/statuses/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li class="active"><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <p id="notice"><%= notice %></p>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-info-circle" aria-hidden="true"></i> Status Info
        </h4>
      </div>
      <div class="panel-body">
      	<p>
		  <strong>Given:</strong>
		  <%= @status.given %>
		</p>

		<p>
		  <strong>Info:</strong>
		  <%= @status.info %>
		</p>
      	<br/>
        <div class="text-center stpad">
        <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_status_path(@status), class:"pull-left btn btn-warning" %>
        <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Statuses'.html_safe, statuses_path, class:"pull-right btn btn-primary" %>

      </div>
	  </div>
      </div>
    </div>
</div>