config/routes.rb
Rails.application.routes.draw do

  resources :departures
  resources :trips
  resources :tracks
  resources :stations
  resources :statuses
  root 'home#index'

end

app/models/departure.rb
class Departure < ActiveRecord::Base
  validates :trip_id, presence: true
  validates :status_id, presence: true
  validates :scheduledtime, presence: true
  has_one :status
  has_one :trip
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  http_basic_authenticate_with name: "MBTAAdmin", password: "MBTA2016"
  before_action :set_departure, only: [:show, :edit, :update, :destroy]

  # GET /departures
  # GET /departures.json
  def index
    @departures = Departure.all
  end

  # GET /departures/1
  # GET /departures/1.json
  def show
  end

  # GET /departures/new
  def new
    @departure = Departure.new
    @departure.scheduledtime = DateTime.now.strftime("%d/%m/%Y %H:%M")
    @status_options = [["Select Status",nil]] + Status.all.map {|st| [st.given, st.id]}
    @trip_options = [["Select Trip",nil]] + Trip.all.map {|tr| ["#{tr.number}: From #{Station.find(tr.origin_id).name} To #{Station.find(tr.destination_id).name}", tr.id]}
  end

  # GET /departures/1/edit
  def edit
    @departure.scheduledtime = DateTime.now.strftime("%d/%m/%Y %H:%M")
    @status_options = [["Select Status",nil]] + Status.all.map {|st| [st.given, st.id]}
    @trip_options = [["Select Trip",nil]] + Trip.all.map {|tr| ["#{tr.number}: From #{Station.find(tr.origin_id).name} To #{Station.find(tr.destination_id).name}", tr.id]}
  end

  # POST /departures
  # POST /departures.json
  def create
    if departure_params[:trip_id] != ""
      trip = Trip.find(departure_params[:trip_id])
      track = Track.find_by(station_id:trip.origin_id, number:departure_params[:track_id])
    end
    @departure = Departure.new(trip_id:departure_params[:trip_id],status_id:departure_params[:status_id],\
      lateness:departure_params[:lateness],info:departure_params[:info],track_id:track ? track.id : nil,\
      scheduledtime:Time.parse(departure_params[:scheduledtime]))

    respond_to do |format|
      if @departure.save
        format.html { redirect_to @departure, notice: 'Departure was successfully created.' }
        format.json { render :show, status: :created, location: @departure }
      else
        @departure.scheduledtime = DateTime.now.strftime("%d/%m/%Y %H:%M")
        @status_options = [["Select Status",nil]] + Status.all.map {|st| [st.given, st.id]}
        @trip_options = [["Select Trip",nil]] + Trip.all.map {|tr| ["#{tr.number}: From #{Station.find(tr.origin_id).name} To #{Station.find(tr.destination_id).name}", tr.id]}
        format.html { render :new }
        format.json { render json: @departure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departures/1
  # PATCH/PUT /departures/1.json
  def update
    if departure_params[:trip_id] != ""
      trip = Trip.find(departure_params[:trip_id])
      track = Track.find_by(station_id:trip.origin_id, number:departure_params[:track_id])
    end
    @departure = Departure.new(trip_id:departure_params[:trip_id],status_id:departure_params[:status_id],\
      lateness:departure_params[:lateness],info:departure_params[:info],track_id:track ? track.id : nil,\
      scheduledtime:Time.parse(departure_params[:scheduledtime]))
    respond_to do |format|
      if @departure.update(departure_params)
        format.html { redirect_to @departure, notice: 'Departure was successfully updated.' }
        format.json { render :show, status: :ok, location: @departure }
      else
        @departure.scheduledtime = DateTime.now.strftime("%d/%m/%Y %H:%M")
        @status_options = [["Select Status",nil]] + Status.all.map {|st| [st.given, st.id]}
        @trip_options = [["Select Trip",nil]] + Trip.all.map {|tr| ["#{tr.number}: From #{Station.find(tr.origin_id).name} To #{Station.find(tr.destination_id).name}", tr.id]}
        format.html { render :edit }
        format.json { render json: @departure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departures/1
  # DELETE /departures/1.json
  def destroy
    @departure.destroy
    respond_to do |format|
      format.html { redirect_to departures_url, notice: 'Departure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departure
      @departure = Departure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departure_params
      params.require(:departure).permit(:scheduledtime,:trip_id, :lateness, :track_id, :info, :status_id)
    end
end

app/views/departures/_departure.html.erb
<% trip = Trip.find(departure.trip_id) %>
<tr>
	<td><%= departure.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
	<td><%= Station.find(trip.origin_id).name %></td>
	<td><%= trip.number %></td>
	<td><%= Station.find(trip.destination_id).name %></td>
	<td><%= departure.scheduledtime.strftime("%d/%m/%Y %H:%M") %></td>
	<td><%= departure.lateness %></td>
	<td><%= departure.track_id ? Track.find(departure.track_id).number : "" %></td>
	<td><%= Status.find(departure.status_id).given %></td>
</tr>

app/views/departures/_departure_admin.html.erb
<% trip = Trip.find(departure.trip_id) %>
<tr>
	<td><%= departure.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
	<td><%= Station.find(trip.origin_id).name %></td>
	<td><%= trip.number %></td>
	<td><%= Station.find(trip.destination_id).name %></td>
	<td><%= departure.scheduledtime.strftime("%d/%m/%Y %H:%M") %></td>
	<td><%= departure.lateness %></td>
	<td><%= departure.track_id ? Track.find(departure.track_id).number : ""%></td>
	<td><%= Status.find(departure.status_id).given %></td>
	<td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, departure, class:"pull-right btn btn-xs btn-info" %></td>
	<td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_departure_path(departure), class:"pull-right btn btn-xs btn-warning" %></td>
  	<td><%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'.html_safe, departure,
               method: :delete,
               data: { confirm: 'Are you sure?' }, class:"pull-right btn btn-xs btn-danger" %></td>
</tr>

app/views/departures/_form.html.erb
<%= form_for(@departure) do |f| %>

  <% if @departure.errors.any? %>
    <%= render partial: "shared/create_errors", locals: {object: @departure, name:"departure"} %>
  <% end %>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Trip</span>
    <%= f.select :trip_id, options_for_select(@trip_options,:selected=>@departure.trip_id),{}, {:class => 'form-control'} %>
  </div>

  <div class="input-group stpad" id='datetimepicker1'>
    <span class="input-group-addon addon3">ScheduledTime</span>
    <%= f.text_field :scheduledtime, class:"form-control",placeholder:"Format: 'Do MMM YYYY HH:mm:ss' E.g. 3rd Fed 2012 07:08:00" %>
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
    </span>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Lateness</span>
    <%= f.number_field :lateness,class:"form-control",placeholder:"In Seconds - Optional" %>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Departure Track #</span>
    <%= f.number_field :track_id,class:"form-control",placeholder:"Enter Track Number" %>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Status</span>
    <%= f.select :status_id, options_for_select(@status_options,:selected=>@departure.status_id),{}, {:class => 'form-control'} %>
  </div>

  <div class="input-group stpad">
    <span class="input-group-addon addon3">Info</span>
    <%= f.text_area :info, class:"form-control", :rows => "2",placeholder:"Optional" %>
  </div>


  <br>
  <div class="text-center stpad">
    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Cancel'.html_safe, departures_path, class:"btn btn-default" %>
    <button role="button" type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-send"></i> Submit</button>

  </div>
<% end %>

app/views/departures/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>

  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-train" aria-hidden="true"></i> Edit Departure
        </h4>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      	<br/>
      	
      	<div class="text-center stpad">
		      <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, @departure, class:"pull-left btn btn-success" %>
	  	    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Departures'.html_safe, departures_path, class:"pull-right btn btn-primary" %>

		    </div>
      </div>
    </div>
</div>

app/views/departures/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-train" aria-hidden="true"></i> Departure Board <span class="badge"><%=@departures.count%></span>
        <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Create New Departure'.html_safe, new_departure_path, class:"pull-right btn btn-success" %>
        </h4>
      </div>
      <div class="panel-body">
      <div class="table-responsive tableItem">
        <table id="table" class="table table-hover table-striped tablesorter">
          <thead>
            <tr>
              <th>Last Update  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Origin  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Trip  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Destination  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>ScheduledTime  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Lateness  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Track  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th>Status  <i class="fa fa-sort text-right" aria-hidden="true"></i></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "departure_admin", collection:@departures, as: :departure %>
          </tbody>
        </table>
      </div>
      </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">

  $(document).ready(function() { 
    $("#table").tablesorter();
  });

</script>

app/views/departures/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-train" aria-hidden="true"></i> New Departure
        </h4>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      	<br/>
      	<%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Departures'.html_safe, departures_path, class:"pull-right btn btn-primary" %>
      </div>
    </div>
</div>


<script type="text/javascript" charset="utf-8">

	// $(function () {
	//     $('#datetimepicker1').datetimepicker({
	//         format: 'Do MMM YYYY HH:mm:ss'
	//     });
	// });

</script>

app/views/departures/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MBTA DepartureBoard</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= departures_path %>">Departures</a></li>
        <li><a href="<%= trips_path %>">Trips</a></li>
        <li><a href="<%= stations_path %>">Stations</a></li>
        <li><a href="<%= tracks_path %>">Tracks</a></li>
        <li><a href="<%= statuses_path %>">Statuses</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container content">
  <%= render "shared/flash" %>
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-train" aria-hidden="true"></i> Departure Info
        </h4>
      </div>
      <div class="panel-body">
        <% trip = Trip.find(@departure.trip_id) %>
        <% track = Track.find_by(station_id:trip.origin_id, number:trip.number) %>
        <p>
        <strong>Trip:</strong>
        <%= "#{trip.number} - From #{Station.find(trip.origin_id).name} To #{Station.find(trip.destination_id).name}" %>
        </p>

        <p>
          <strong>Lateness:</strong>
          <%= @departure.lateness %> seconds
        </p>

        <p>
          <strong>Track #:</strong>
          <%= @departure.track_id ? Track.find(@departure.track_id).number : "" %>
        </p>

        <p>
          <strong>Info:</strong>
          <%= @departure.info %>
        </p>

        <p>
          <strong>Status:</strong>
          <%= Status.find(@departure.status_id).given %>
        </p>
        <br/>
        <div class="text-center stpad">
        <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'.html_safe, edit_departure_path(@departure), class:"pull-left btn btn-warning" %>
        <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back To Departures'.html_safe, departures_path, class:"pull-right btn btn-primary" %>

      </div>
      </div>
    </div>
</div>